CREATE DATABASE collector;
USE collector;
CREATE TABLE ips (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR (232),
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);